# Generated by Django 2.0.dev20170318191452 on 2017-03-23 05:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall', models.CharField(choices=[('1', '1501'), ('2', '1502'), ('3', '1503'), ('4', '1504'), ('5', '1505'), ('6', '1506'), ('7', '1507')], max_length=2)),
                ('side', models.CharField(choices=[('AD', 'A/D Side'), ('BC', 'B/C Side')], max_length=10)),
                ('machine_type', models.CharField(choices=[('W', 'Washer'), ('D', 'Dryer')], max_length=10)),
                ('time_required', models.DurationField()),
                ('time_start', models.DateTimeField(blank=True, null=True)),
                ('availabilities', models.CharField(choices=[('Available', 'Available'), ('In Use', 'In Use'), ('Cycle Complete', 'Cycle Complete'), ('Unavailable', 'Unavailable')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Queue_Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_queue', to='laundry.Machine')),
            ],
        ),
    ]
